# Generated by Django 3.2.3 on 2026-01-16 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Blog', '0002_auto_20210609_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_title', models.CharField(max_length=264, verbose_name='Recipe Title')),
                ('slug', models.SlugField(max_length=264, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Recipe Description')),
                ('ingredients', models.TextField(verbose_name='Ingredients (one per line)')),
                ('instructions', models.TextField(verbose_name='Cooking Instructions')),
                ('servings', models.IntegerField(default=4)),
                ('prep_time', models.IntegerField(default=15, help_text='Prep time in minutes')),
                ('cook_time', models.IntegerField(default=30, help_text='Cook time in minutes')),
                ('recipe_image', models.ImageField(upload_to='recipe_images', verbose_name='Recipe Image')),
                ('public_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-public_date'],
            },
        ),
    ]
