# Generated by Django 3.2.3 on 2026-01-16 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HormonalTwin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_issue', models.CharField(choices=[('PCOS', 'Polycystic Ovary Syndrome (PCOS)'), ('Endometriosis', 'Endometriosis'), ('Thyroid', 'Thyroid Disorder'), ('Irregular_Cycle', 'Irregular Menstrual Cycle'), ('Heavy_Bleeding', 'Heavy Menstrual Bleeding'), ('Hormonal_Acne', 'Hormonal Acne'), ('Low_Estrogen', 'Low Estrogen'), ('High_Testosterone', 'High Testosterone'), ('PMS', 'Premenstrual Syndrome (PMS)'), ('PMDD', 'Premenstrual Dysphoric Disorder (PMDD)'), ('Perimenopause', 'Perimenopause'), ('Other', 'Other Hormonal Issues')], max_length=50)),
                ('secondary_issues', models.CharField(blank=True, help_text='Comma-separated list of other issues', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Share a bit about your journey', max_length=500)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='twin_profiles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hormonal_twin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TwinConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, help_text='Optional message when connecting', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twin_connections_sent', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twin_connections_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user1', 'user2')},
            },
        ),
    ]
