# Generated by Django 3.2.3 on 2026-01-19 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='symptom',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='symptom',
        ),
        migrations.AddField(
            model_name='period',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='flow',
            field=models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy'), ('spotting', 'Spotting')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='period',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='period',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symptom',
            name='mood',
            field=models.CharField(blank=True, choices=[('happy', '😊 Happy'), ('sad', '😢 Sad'), ('anxious', '😰 Anxious'), ('irritable', '😤 Irritable'), ('tired', '😴 Tired'), ('energetic', '⚡ Energetic'), ('normal', '😐 Normal')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='symptom_type',
            field=models.CharField(choices=[('cramps', 'Cramps/Pain'), ('headache', 'Headache'), ('bloating', 'Bloating'), ('fatigue', 'Fatigue'), ('nausea', 'Nausea'), ('backache', 'Back Pain'), ('breast_tenderness', 'Breast Tenderness'), ('mood_swings', 'Mood Swings'), ('acne', 'Acne/Skin Issues'), ('cravings', 'Food Cravings'), ('insomnia', 'Sleep Issues'), ('diarrhea', 'Digestive Issues'), ('other', 'Other')], default='other', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='period',
            name='cycle_length',
            field=models.IntegerField(default=28),
        ),
        migrations.AlterField(
            model_name='period',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='severity',
            field=models.IntegerField(help_text='Rate from 1 (mild) to 10 (severe)'),
        ),
    ]
